name: MkDocs Build and Deploy

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy MkDocs
        uses: Reloaded-Project/devops-mkdocs@v1
        with:
          requirements: ./source/docs/requirements.txt
          config-file: ./source/mkdocs.yml
          publish-to-pages: ${{ github.event_name == 'push' }}
          checkout-current-repo: true
