name: Build and Deploy MkDocs

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: MkDocs Build
        uses: romw314/mkdocs-action@v9
        with:
          output-dir: site
          workdir: mkdocs
